language: c
sudo: true

deploy:
  provider: pypi
  user: bgruening
  skip_existing: true
  password:
    secure: umDRCnyugr5/Tuq/81TQ9Lmk/SJBTU8BEh1cQIvHW7b0gN+DtT13Fl2DKtlZUlgXkp+aKbQs5TpBsZ+WDs8KJUVNpfflEh0cdiEG9x/olyhfe3a9i+y7WxAZBUZtzKTTwqgCRzm72S+lh7avxuJx5JRoXwhKWV4N3hvUl180jo+AjYdg3opXHFAU0IA4234k4TcMTM+z58GBNyPdH1YRZ6nwGi+S3lib6ctiNcpZRZhQ3o8gallr4Exmuqf4gmDPbLM7Rn0o+37lA43nt9gXO2oy7bvooTKYsIolXy2v7QmrE6kU6H70RhO4CdDxXqmVO2C8em+wj96W05/4pu65UhPExM6y/x1EztrMOd65+oVvXyNFt2SDPMk+mR5AjLbzhQIYyJpu23vSXvd+PLhy2OY27QzGTZ2Qpo3phBUBUrjINNHqvfteoaLADvLDXB9VngFJ+JK435t5jpGlpRHkHdpA1mtOnH7FsGSAE4MqFUA+GwH+eBqPzwBe8jhYwzPkV+9ivnGuYG7JOGp+mX5O9lhh/cQ5Wkv19Wzoj1512LRPX1Y3frw09K+tfgw0RahrAVydRnbRibO2tOtI2ulZVGTjXekYZAJKQBtG1/HlYv5xaRUaWPQPQuwnuSe1Aq4VcXt6BvFrIK5ZifKtyQkW79XUiikISFs9F0qd58DmU+A=
  on:
    tags: true
  distributions: sdist bdist_wheel
  python:
    - 3.6
    - 3.7
env:
- TRAVIS_PYTHON_VERSION=3.6
- TRAVIS_PYTHON_VERSION=3.7

os:
- linux
- osx
jobs:
  include:
  - stage: lint
    env:
    - LINT=1
    - TRAVIS_PYTHON_VERSION=3.6
    - TRAVIS_OS_NAME=linux
    before_install:
    - curl https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o
      miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - PATH_WITHOUT_CONDA="$PATH"
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    install:
    - conda install --yes python=$TRAVIS_PYTHON_VERSION flake8
    script:
    - if [[ "$LINT" == "1" ]]; then flake8 . --exclude=.venv,.build,build --ignore=E501,F403,E402,F999,F405,E712
      ; fi
before_install:
- export TEST_DATA_DIR="`pwd`/pygenometracks/test/test_data/"
- echo $TEST_DATA_DIR
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
  curl https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o miniconda.sh
  ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl
  https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -o miniconda.sh
  ; fi
- bash miniconda.sh -b -p $HOME/miniconda
- PATH_WITHOUT_CONDA="$PATH"
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
install:
- conda install --yes -c bioconda -c conda-forge python=$TRAVIS_PYTHON_VERSION --file requirements.txt
- python setup.py install
script:
- py.test pygenometracks --doctest-modules
