language: c
sudo: true

env:
  - TRAVIS_PYTHON_VERSION=3.6

os:
  - linux
  - osx

jobs:
  include:
    - stage: lint
      env:
        - LINT=1
        - TRAVIS_PYTHON_VERSION=3.6
        - TRAVIS_OS_NAME=linux
      before_install:
        - curl https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -o miniconda.sh
        - bash miniconda.sh -b -p $HOME/miniconda
        - PATH_WITHOUT_CONDA="$PATH"
        - export PATH="$HOME/miniconda/bin:$PATH"
        - hash -r
        - conda config --set always_yes yes --set changeps1 no
        - conda update -q conda
      install:
        - conda install --yes python=3.6 flake8
      script:
        - if [[ "$LINT" == "1" ]]; then flake8 . --exclude=.venv,.build,build --ignore=E501,F403,E402,F999,F405,E712 ; fi

# Setup anaconda
before_install:
  - export TEST_DATA_DIR="`pwd`/pygenometracks/test/test_data/"
  - echo $TEST_DATA_DIR
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then curl https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o miniconda.sh ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then curl https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -o miniconda.sh ; fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - PATH_WITHOUT_CONDA="$PATH"
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

# Install packages
install:
  - conda install --yes -c bioconda -c conda-forge python=$TRAVIS_PYTHON_VERSION --file requirements.txt
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then conda install --yes -c bioconda -c conda-forge -c defaults configparser ; fi
  - python setup.py install

# command to run tests
script:
  - py.test pygenometracks --doctest-modules
