# create the environment using : `conda env create -f environment.yml`
# update existing environment using : `conda env update -f environment.yml`
# It installs from source using github master branch. If you get a pip error coming from feedparser.py, refer to the hack mentioned here : `https://bugs.python.org/msg301789`
name: pygenometracks
channels:
   - bioconda
   - conda-forge
dependencies:
    - numpy >=1.16
    - matplotlib >=3.1.1,<=3.2.2
    - intervaltree >=2.1.0
    - pybigwig >=0.3.16
    - future >=0.17.0
    - hicmatrix >=15
    - pysam >=0.14
    - pytest
    - gffutils >=0.9
    - pybedtools >=0.8.1
    - tqdm >=4.20
    - bx-python >=0.8.13
    - pip:
        - "git+https://github.com/deeptools/pyGenomeTracks.git"
